In [4]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import pandas as pd

In [5]:
data_dir = "../Data/"

In [36]:
train_df = pd.read_csv(data_dir+"train.csv")
test_df = pd.read_csv(data_dir+"test.csv")

In [17]:
train_df[train_df.columns[train_df.dtypes=='float64']].describe()


target     48df886f9     34b15f335     20aa07010     dc5a8f1d8  \
count  4.459000e+03  4.459000e+03  4.459000e+03  4.459000e+03  4.459000e+03   
mean   5.944923e+06  1.465493e+04  2.672245e+04  2.569407e+06  1.552158e+05   
std    8.234312e+06  3.893298e+05  5.699652e+05  9.610183e+06  1.587815e+06   
min    3.000000e+04  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    6.000000e+05  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    2.260000e+06  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    8.000000e+06  0.000000e+00  0.000000e+00  6.000000e+05  0.000000e+00   
max    4.000000e+07  2.000000e+07  2.000000e+07  3.196120e+08  6.000000e+07   

          11d86fa6a     cff75dd09     b8a716ebf     f3b9c0b95     68b647452  \
count  4.459000e+03  4.459000e+03  4.459000e+03  4.459000e+03  4.459000e+03   
mean   1.950500e+05  4.588255e+04  3.968961e+05  4.483841e+05  1.128254e+05   
std    2.397372e+06  8.140674e+05  3.238243e+06  6.370644e+06  1.161275e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    1.000000e+08  3.111000e+07  1.000000e+08  2.000000e+08  3.720000e+07   

           ...          2a879b4f7     6b119d8ce     7ad6b38bd     85dcc913d  \
count      ...       4.459000e+03  4.459000e+03  4.459000e+03  4.459000e+03   
mean       ...       1.004851e+05  3.825025e+05  9.648562e+04  7.599802e+04   
std        ...       9.150068e+05  2.799848e+06  1.114863e+06  1.206581e+06   
min        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max        ...       2.400000e+07  5.000000e+07  4.000000e+07  5.000000e+07   

          8d8bffbae     5831f4c76     a165f5761     3ecc09859     9281abeea  \
count  4.459000e+03  4.459000e+03  4.459000e+03  4.459000e+03  4.459000e+03   
mean   5.302810e+05  1.247793e+06  1.289495e+05  4.676057e+05  4.446239e+05   
std    4.497567e+06  6.878895e+06  1.335938e+06  4.068038e+06  4.428889e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    1.500000e+08  1.601600e+08  4.528000e+07  7.600000e+07  1.235880e+08   

          8675bec0b  
count  4.459000e+03  
mean   8.056219e+05  
std    4.513246e+06  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    0.000000e+00  
max    1.300000e+08  

[8 rows x 1845 columns]

In [18]:
test_df[test_df.columns[test_df.dtypes=='float64']].describe()

48df886f9     0deb4b6a8     34b15f335     a8cb14b00     2f0771a37  \
count  4.934200e+04  4.934200e+04  4.934200e+04  4.934200e+04  4.934200e+04   
mean   5.773787e+04  6.258726e+04  1.036752e+05  6.289853e+04  6.713354e+04   
std    1.745182e+06  2.322787e+06  2.586951e+06  2.765941e+06  3.206124e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    1.504447e+08  2.283295e+08  2.758171e+08  3.972621e+08  4.667591e+08   

          30347e683     d08d1fbe3     6ee66e115     20aa07010     dc5a8f1d8  \
count  4.934200e+04  4.934200e+04  4.934200e+04  4.934200e+04  4.934200e+04   
mean   8.083879e+04  6.181014e+04  5.515752e+04  1.406324e+06  8.128668e+04   
std    2.845031e+06  2.780137e+06  1.923517e+06  6.872366e+06  2.378938e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    2.852223e+08  4.863751e+08  2.043290e+08  3.435658e+08  2.310167e+08   

           ...          3ecc09859     9281abeea     8675bec0b     3a13ed79a  \
count      ...       4.934200e+04  4.934200e+04  4.934200e+04  4.934200e+04   
mean       ...       1.193910e+05  1.355955e+05  3.242217e+05  1.437856e+05   
std        ...       3.115190e+06  2.598454e+06  3.782996e+06  3.663374e+06   
min        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max        ...       5.351692e+08  1.236547e+08  3.793398e+08  4.025480e+08   

          f677d4d13     71b203550     137efaa80     fb36b89d9     7e293fbaf  \
count  4.934200e+04  4.934200e+04  4.934200e+04  4.934200e+04  4.934200e+04   
mean   9.302367e+04  8.047145e+04  6.076865e+04  1.323210e+05  1.675766e+05   
std    5.041000e+06  2.100210e+06  2.040655e+06  3.592018e+06  3.761816e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    9.657530e+08  1.680065e+08  2.497913e+08  3.200000e+08  3.186300e+08   

          9fc776466  
count  4.934200e+04  
mean   1.282487e+05  
std    2.413798e+06  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    0.000000e+00  
max    2.189782e+08  

[8 rows x 4991 columns]

In [37]:
id_train = train_df["ID"]
id_test = test_df["ID"]
target = train_df["target"]

train_df.drop(["target","ID"],inplace=True, axis=1)
test_df.drop(["ID"],inplace=True, axis=1)

In [27]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_val_score

In [66]:
def rmsle(val, pred):
    "Root mean square logarithmic error"
    val=np.array(val)
    pred=np.array(pred)
    total = 0.0
    n=len(val)
    for i in range(n):
        if val[i] < 0 or pred[i]<0:
            continue
        else:    
            log_v = np.log(val[i]+1)
            log_p = np.log(pred[i]+1)  
            total+= (log_p-log_v)**2
    return np.sqrt(total/n)    

def rmsle_test(val, pred):
    return np.sqrt(np.mean(np.power(np.log(val+1)-np.log(pred+1), 2)))

In [67]:
rmsle_score = make_scorer(rmsle_test, greater_is_better=False)

In [44]:
rf=RandomForestRegressor(n_estimators=1000, oob_score=True,n_jobs=-1, 
                         random_state=42, max_features=None, min_samples_leaf=50)

In [46]:
#rf_scores = cross_val_score(rf, train_df, target, cv=3, scoring=rmsle_score)

In [47]:
rf.fit(train_df, target)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=None, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=50, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=-1,
           oob_score=True, random_state=42, verbose=0, warm_start=False)

In [48]:
preds=rf.predict(test_df)

In [55]:
len(target),len(preds)

(4459, 49342)

In [63]:
from sklearn.model_selection import train_test_split

In [68]:
cross_val_score(rf, train_df, target,scoring=rmsle_score)

array([-1.83663847, -1.83684514, -1.91435827])

In [69]:
scores_test=[-1.83663847, -1.83684514, -1.91435827]

In [70]:
np.exp(scores_test)

array([0.15935219, 0.15931926, 0.14743642])

In [72]:
sub = pd.read_csv(data_dir+"sample_submission.csv")
sub['target'] = preds
sub.to_csv('sub_rfc_test.csv', index=False)

In [74]:
clf=RandomForestRegressor(n_estimators=1000, oob_score=True,n_jobs=-1, 
                         random_state=42, max_features=None, min_samples_leaf=50)

In [75]:
clf.fit(train_df, target)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=None, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=50, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=-1,
           oob_score=True, random_state=42, verbose=0, warm_start=False)

In [76]:
clf.feature_importances_

array([0., 0., 0., ..., 0., 0., 0.])

In [82]:
clf.feature_importances_[np.argsort(-clf.feature_importances_)]

array([0.29043448, 0.11035547, 0.07931199, ..., 0.        , 0.        ,
       0.        ])

In [83]:
train_df.columns[np.argsort(-clf.feature_importances_)]

Index(['f190486d6', 'eeb9cd3aa', '58e2e02e6', '15ace8c9f', 'b43a7cfd5',
       '58232a6fb', '9fd594eec', '20aa07010', 'f74e8f13d', '024c577b9',
       ...
       '625525b5d', 'dee843499', 'c30ff7f31', '9e711a568', '8348ea8d3',
       '3027b873d', 'c3825b569', '3305c8063', 'bea06dade', '9fc776466'],
      dtype='object', length=4991)

In [84]:
clf.oob_score_

0.23503269393006931

In [86]:
clf.oob_prediction_

array([6629925.09398079, 4576886.72677292, 5329360.39129442, ...,
       5260032.45299233, 3004678.02983218, 9865519.24672082])

In [87]:
preds2=clf.predict(test_df)

In [89]:
from sklearn.metrics import accuracy_score

In [93]:
diff=preds2-preds
diff[np.argsort(-diff)]

array([ 7.45058060e-09,  7.45058060e-09,  7.45058060e-09, ...,
       -7.45058060e-09, -7.45058060e-09, -1.11758709e-08])

In [94]:
unique_df = train_df.nunique().reset_index()
unique_df.columns = ["col_name", "unique_count"]
constant_df = unique_df[unique_df["unique_count"]==1]
constant_df.shape

(256, 2)

In [95]:
train_no_cont=train_df.drop(constant_df.col_name.tolist(), axis=1)

In [96]:
clf2=RandomForestRegressor(n_estimators=1000, oob_score=True,n_jobs=-1, 
                         random_state=42, max_features=None, min_samples_leaf=50)

In [97]:
clf2.fit(train_df, target)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=None, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=50, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=-1,
           oob_score=True, random_state=42, verbose=0, warm_start=False)

In [98]:
preds3=clf2.predict(test_df)

In [99]:
diff=preds3-preds
diff[np.argsort(-diff)]

array([ 7.4505806e-09,  7.4505806e-09,  7.4505806e-09, ...,
       -7.4505806e-09, -7.4505806e-09, -7.4505806e-09])

In [100]:
from scipy.stats import randint as sp_randint
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV


In [101]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [ ]:
clf3=RandomForestRegressor(oob_score=True,n_jobs=-1, 
                         random_state=42, max_features=None)

param_grid = {
              "n_estimators": [1000,2000],
              "min_samples_leaf": [50,100],
              }
grid_search = GridSearchCV(clf3, param_grid=param_grid, scoring=rmsle_score,n_jobs=-1)

grid_search.fit(train_df, target)


In [105]:
report(grid_search.cv_results_)

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.